### ISSUE TITLE
Bomb bot

### ISSUE THREAD

**Issue by jasonchadwick** [jasonchadwick/chronodrifter#25]
Circular bot that constantly rolls towards the player. Could either be time-reversible or not.

Variants:
- Reversible: explosion can be reversed, and bomb bot comes back to life.
- Irreversible: explosion cannot be reversed, and every object that is hit by explosion becomes irreversible as well.

**Comment by ProgramInc** [comment]
Hi! Can I contribute to your project? if it's OK, please assign me this issue

**Comment by jasonchadwick** [comment]
@ProgramInc Thanks for the interest, it means a lot! Since the project is still pretty new, I am currently limiting contributions to people I already know. In the future, when we have the game more developed, I am potentially interested in allowing new collaborators, but for now I'm going to keep it to a smaller group. Sorry! If you're still interested in a few months, check back and we will see where we're at.

**Comment by ProgramInc** [comment]
@jasonchadwick Thanks for your reply! I'll check with you again in the future!
